### PR TITLE
Fix safe version and refactor safe deployments functions

### LINKED ISSUE #165: SafeFactory only deploys version 1.3.0
## Description

I'd like to deploy older safes to test my application when users are using older safe contract versions. However, I cannot deploy a safe lower than version 1.3.0. 

## Environment

- Safe Core SDK version: 2.0.0
- Safe contract version: 1.1.1 (desired)
- Environment:
  - browser: chrome

## Steps to reproduce

```
const safeVersion = '1.1.1'
const safeFactory = SafeFactory.create({
    ethAdapter,
    safeVersion,
  });
const safeAccountConfig: SafeAccountConfig = {
    owners: ['0xa...', '0xb...'],
    threshold: 1,
};
const safe = await safeFactory.deploySafe({ safeAccountConfig });
console.log(await safe.getContractVersion())
```
The resulting safe created is always contract version 1.3.0

## Expected result

I expect the contract version to match the `safeVersion` input to `SafeFactory.create`

### PR DESCRIPTION
**Pull request by germartinez**
## What it solves
Resolves #165 

## How this PR fixes it:
- In the `SafeFactory` class, inside the method `getContract` was a call to the method `getSafeContractDeployment` where the safeVersion was set to the last current version. This was wrong.

- Refactor the methods that return the instances of the Safe contracts:
  - The methods `getProxyFactoryContract`, `getMultiSendContract` and `getSafeContract` were extracted to a different file.
  - There were two different implementations of `getSafeContract` before (one with `customSafeAddress` as a prop and other without it). These two were also merged in one.

### CODE REVIEW

File: packages/safe-core-sdk/src/contracts/safeDeploymentContracts.ts [hunk 1]
```diff
@@ -7,8 +13,32 @@ import {
   getSafeSingletonDeployment,
   SingletonDeployment
 } from '@gnosis.pm/safe-deployments'
+import { ContractNetworkConfig } from '../types'
 import { safeDeploymentsL1ChainIds, safeDeploymentsVersions } from './config'
 
+interface GetSafeContractInstanceProps {
```
Comment (iamacook) [inline packages/safe-core-sdk/src/contracts/safeDeploymentContracts.ts:19]: There seems to be some repetition in these types? Maybe it's worthwhile making a base `ContractInstanceProps` type?

File: packages/safe-core-sdk/src/contracts/safeDeploymentContracts.ts [hunk 2]
```diff
@@ -37,3 +67,70 @@ export function getSafeProxyFactoryContractDeployment(
...
+  const gnosisSafeContract = ethAdapter.getSafeContract({
+    safeVersion,
+    chainId,
+    singletonDeployment,
+    customContractAddress: customSafeAddress ?? customContracts?.safeMasterCopyAddress,
+    customContractAbi: customContracts?.safeMasterCopyAbi
+  })
+  const isContractDeployed = await ethAdapter.isContractDeployed(gnosisSafeContract.getAddress())
+  if (!isContractDeployed) {
+    throw new Error('Safe Proxy contract is not deployed in the current network')
```
Comment (iamacook) [inline packages/safe-core-sdk/src/contracts/safeDeploymentContracts.ts:89]: The three error messages here should be "...deployed on the current network"

**Review by iamacook — APPROVED** [review]
Looks good to me 🚀  Just a couple of suggestions

**Review by iamacook — APPROVED** [review]
💪
